version: '3.8'

services:
  web:
    image: php:7.4-apache
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 593
      POSTGRES_DB: Concesionario_Tractores
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
