global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["web:8081"]  # Target del servicio web
  - job_name: postgres-exporter
    static_configs:
      - targets: ["postgres-exporter:9187"]  # Target del exporter de PostgreSQL

